let shopItemsData = [
  {
    id: "adcca",
    title: "iPhone 7 Plus",
    category: "Mobiles",
    price: 250,
    img: "../images/mob1.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccb",
    title: "Samsung Galaxy Tab S3",
    category: "Mobiles",
    price: 160,
    img: "../images/mob2.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccc",
    title: "Samsung Galaxy S9",
    category: "Mobiles",
    price: 160,
    img: "../images/mob3.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccd",
    title: "Huawei nova 2",
    category: "Mobiles",
    price: 100,
    img: "../images/mob4.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adcce",
    title: "IPhone 8 Plus",
    category: "Mobiles",
    price: 300,
    img: "../images/mob5.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccf",
    title: "LTE Dual SIM 4G",
    category: "Mobiles",
    price: 110,
    img: "../images/mob6.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccg",
    title: "Headset Xbox 360",
    category: "Electronics",
    price: 200,
    img: "../images/ele1.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adcch",
    title: "Headphones Logitech G433",
    category: "Electronics",
    price: 100,
    img: "../images/ele2.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adcci",
    title: "Sony Headphones",
    category: "Electronics",
    price: 120,
    img: "../images/ele3.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccj",
    title: "Beats Solo3 Wireless",
    category: "Electronics",
    price: 300,
    img: "../images/ele4.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adcck",
    title: "Apple Watch Series 3",
    category: "Electronics",
    price: 260,
    img: "../images/ele5.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccl",
    title: "Lenovo Yoga IdeaPad",
    category: "Electronics",
    price: 300,
    img: "../images/ele6.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccm",
    title: "HP Pavilion Windows 10",
    category: "Electronics",
    price: 240,
    img: "../images/ele7.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adccn",
    title: "Blazer blue",
    category: "Fashion",
    price: 150,
    img: "../images/fash1.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },

  {
    id: "adcc0",
    title: "Polo Tshirt",
    category: "Fashion",
    price: 800,
    img: "../images/fash2.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccp",
    title: "Denim jacket",
    category: "Fashion",
    price: 50,
    img: "../images/fash3.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccq",
    title: "Denim Short",
    category: "Fashion",
    price: 40,
    img: "../images/fash4.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccr",
    title: "Bag",
    category: "Fashion",
    price: 180,
    img: "../images/fash5.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccs",
    title: "Puff Jacket",
    category: "Fashion",
    price: 100,
    img: "../images/fash6.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adcct",
    title: "Leather wallet",
    category: "Fashion",
    price: 40,
    img: "../images/fash7.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccu",
    title: "Night Lamp",
    category: "Home",
    price: 70,
    img: "../images/hom1.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccv",
    title: "Cloth stand",
    category: "Home",
    price: 100,
    img: "../images/hom2.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccw",
    title: "Sofa chair",
    category: "Home",
    price: 200,
    img: "../images/hom3.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccx",
    title: "Mattress",
    category: "Home",
    price: 100,
    img: "../images/hom4.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccy",
    title: "Pot storage",
    category: "Home",
    price: 30,
    img: "../images/hom5.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adccz",
    title: "Plant Pot",
    category: "Home",
    price: 20,
    img: "../images/hom6.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  },
  {
    id: "adcaa",
    title: "Juicer",
    category: "Home",
    price: 60,
    img: "../images/hom7.png",
    desc: "Lorem ipsum dolor, sit amet consectetur adipisicing elit. Facere.",
  }
];
